site_name: Pylord
site_description: Pylord, Python Web Framework built for creating APIs
site_url: https://pylord.uz

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - version.dropdown       # 🔥 add version selector

  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en

repo_name: ravshanovdev/pylord
repo_url: https://github.com/ravshanovdev/pylord

plugins:
  search:
  social:
  macros:
    include_yaml:
      - sponsors: data/sponsors.yml
      - members: data/members.yml
  mike:                   # 🔥 versioning
    version_selector: true
    alias_type: redirect
    canonical_version: latest

nav:
  - Pylord: index.md
  - features.md
  - Learn:
      - learn/index.md
      - databases.md
      - db-to-code.md
      - environment-variables.md
      - virtual-environments.md
      - install.md
      - Tutorial - User Guide:
          - tutorial/index.md
          - tutorial/create-db-and-table-with-db-browser.md
          - tutorial/create-db-and-table.md
          - tutorial/insert.md
          - tutorial/automatic-id-none-refresh.md
          - tutorial/select.md
          - tutorial/where.md
          - tutorial/indexes.md
          - tutorial/one.md
          - tutorial/limit-and-offset.md
          - tutorial/update.md
          - tutorial/delete.md
          - Connect Tables - JOIN:
              - tutorial/connect/index.md
              - tutorial/connect/create-connected-tables.md
              - tutorial/connect/create-connected-rows.md
              - tutorial/connect/read-connected-data.md
              - tutorial/connect/update-data-connections.md
              - tutorial/connect/remove-data-connections.md
          - Relationship Attributes:
              - tutorial/relationship-attributes/index.md
              - tutorial/relationship-attributes/define-relationships-attributes.md
              - tutorial/relationship-attributes/create-and-update-relationships.md
              - tutorial/relationship-attributes/read-relationships.md
              - tutorial/relationship-attributes/remove-relationships.md
              - tutorial/relationship-attributes/back-populates.md
              - tutorial/relationship-attributes/cascade-delete-relationships.md
              - tutorial/relationship-attributes/type-annotation-strings.md
          - Many to Many:
              - tutorial/many-to-many/index.md
              - tutorial/many-to-many/create-models-with-link.md
              - tutorial/many-to-many/create-data.md
              - tutorial/many-to-many/update-remove-relationships.md
              - tutorial/many-to-many/link-with-extra-fields.md
          - tutorial/code-structure.md
          - FastAPI and Pydantic:
              - tutorial/fastapi/index.md
              - tutorial/fastapi/simple-hero-api.md
              - tutorial/fastapi/response-model.md
              - tutorial/fastapi/multiple-models.md
              - tutorial/fastapi/read-one.md
              - tutorial/fastapi/limit-and-offset.md
              - tutorial/fastapi/update.md
              - tutorial/fastapi/update-extra-data.md
              - tutorial/fastapi/delete.md
              - tutorial/fastapi/session-with-dependency.md
              - tutorial/fastapi/teams.md
              - tutorial/fastapi/relationships.md
              - tutorial/fastapi/tests.md
      - Advanced User Guide:
          - advanced/index.md
          - advanced/decimal.md
          - advanced/uuid.md
  - Resources:
      - resources/index.md
      - help.md
      - contributing.md
      - management-tasks.md
  - About:
      - about/index.md
      - alternatives.md
      - management.md
  - release-notes.md

markdown_extensions:
  abbr:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true

  pymdownx.betterem:
    smart_enable: all
  pymdownx.caret:
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite:
  pymdownx.keys:
  pymdownx.mark:
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tilde:

  pymdownx.blocks.admonition:
    types:
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      - info
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: true

  mdx_include:
  markdown_include_variants:

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ravshanovdev/pylord
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pylord
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pylord
    - icon: fontawesome/brands/dev
      link: https://dev.to/pylord
    - icon: fontawesome/brands/medium
      link: https://medium.com/@pylord
    - icon: fontawesome/solid/globe
      link: https://pylord.uz

extra_css:
  - stylesheets/pylord.css
